#!/bin/bash
#
# Copyright (c) 2011 by Jacek Krysztofik <jacek.krysztofik@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

INSTALL_PREFIX="/usr/local"

if [ -z "$1" ]; then
    echo "Usage: $0 \"site_name\" [template-name]"
    exit
fi

# check access
SITES_DIR=/etc/apache2/sites-available
if [ ! -w ${SITES_DIR} ]; then
    echo "access denied - be a `stat -c '%U' $SITES_DIR`"
    exit 1
fi

# choose template
TEMPLATE_DIR=${INSTALL_PREFIX}/share/mkvhost/templates
if [ ! -z "$2" -a -r "${TEMPLATE_DIR}/$2" ]; then
    TEMPLATE_NAME="${TEMPLATE_DIR}/$2"
else
    TEMPLATE_NAME="${TEMPLATE_DIR}/default"
fi

SITE_NAME=`echo "$1" | sed -r 's/.*/\L&/; s/\s+/-/'`
echo Creating "${SITE_NAME}" VirtualHost

# vhost config
sed -r "s/:template:/${SITE_NAME}/g" < ${TEMPLATE_NAME} > ${SITES_DIR}/${SITE_NAME}

# check if the service name is known
# Add url local in /etc/hosts
host -4 ${SITE_NAME} || gethostip -d ${SITE_NAME} || $(
    SERVER_NAME="${SITE_NAME}.local"
    echo "127.0.0.1 ${SITE_NAME} ${SERVER_NAME}" >> /etc/hosts
    echo "::1 ${SITE_NAME} ${SERVER_NAME}" >> /etc/hosts
    )

# Enable the vhost
a2ensite ${SITE_NAME}

# Reload Apache2
/etc/init.d/apache2 reload

